
console.log('hey')

let boys = 0
let girls = 0
for (let i = 0; i < 1000; i++) {
    while (true) {
        let boy = Math.random() >= 0.5
        if (boy) {
            boys++
        } else {
            girls++
            break
        }
    }
}
console.log({boys,girls})

// // let text = "srASBpeThwTwhdZVPOaECJhGnxhRKzxrbMSDyGZGNZBbCOKvPpJKKaQEcoLGBfIiKtpVsROccWwgrWdEqtNFskeDnFbfKWVEeLvtBUlWrOMgtxsaSkctfJQfdOGRNMzeBlFsCFafWXzvrGfazhEruTMOETzZRYnuHsrtHeYivQdXFnwdDslSSGpfOMyrhbgkOnPiwDTzUBbRaJzGbvUGmVzzTPRaXmLZsXyElKjzwXUYUqiuggHiSzHiGSuQhgHTICVWIjVXMUXOQhPdEskSprJHQvvtRtNQEVUwkGGqDUrAXzWTMyUYIisiOxlTHcIsFfSnhzmCgEwmoWChrqkyNdtdLFWErzlEprlTNZsPfedCDEsqvmLWmxgCxpmSPTjGSxtXINfaDztBUNdiQWoaIgFkqajwhInhMzczvmTJjwgtSGGoIbozCJgVurJetNXSXWeduNjPVlpZtDimsizGqUjaLjYWvlRdYdrWvHzNUnKOlAUpTBMkUNFqYLvQKoQiPPwvndXenRCVaBotNEKkJPUrYnaWAgizfeHyQMoFICbCqKELTmUYvqPYpzKVBYPTLxRLMyexgApRCWDjhQAsDQhRGStiyGMEAWoBLFpsdbGGxFbgIarMglYofcZXILlFlCvkCkCXybTKiYrHLpWXbngLJyVIzhwPIqSQlHURyrrtBTUbyrmMEquLvVjfKrRzTzVoiknxpIICbQGfptEtwvpvUkeqOvtCOuArDtavZFszWBStWtqEGLIdKuVMTFRXhOWPpjHcEWmthjrKXEnfeNKDmPEyvneMQrDBGZdibvyCCFlfMFPsXhhADOZwmmoJkqsyNaPoKLuPsaLzvkpkVbRiAfOxsECFcuLWpfNPkfgIbpAuEXEoHLtrWtLJmHEMIxsvZVryZQxcUgnZgDSlXjSroSBAiwpkqgiCVksMaVuhZpIqhDQglSmjUqYYAzQSvorxlrNMeOYUFakgkhJfKQPBYKdSLYHKlcEWaqINpRgogVCQBAktVDZznrSikzvSRmFCdJsaNSGnQZPPEZSizcsqcPMirBkJzFkVrVVNOlDSygFlmnjhcGuZdRVhTlsJmchZCQJUurVMEfaBDKqEfyXyzequOleOzwxDXxoXifpLtFbGtkyTbVSStjeSKviMhjsuDVKrKOJYOgwIxLODEsHrMPyBWKRPfEugIYXXghDvyXPUBvSQPHRusscQDhaxmJnUnsfGHZANXdffxdeTLxvAuAPOcaSotONXBxiyFMSMUUpFGMYKWVFGttqfsNUDfTIrWSVVeQhpvFRypLgpgIEuMssFOnCoNophSDWgFbIGpEkQbrPzWYlZLkcMWfoKLNqbyJREvFRlwFbDViVIIvZUtQzolDSNdUiSKyGjTiGWyUqbXxTApqMkulpxgcYFmzLnqDaWObWOVTkXoabkzrWaZUDyyTyndqAeJheDPOYuAnKwmUatXgcRRGekDvtigtfLQHqVFJBrifkYlHdjUXLamveLrZpNbsEbQUvhArMkvClLdhHYyQNtxFIMFKriMTJUeJowIEieTzdADsgnJFDgGwkRjUXQXxkLOUsYMcThlYixSicfCrhFcxUSFOMCvsvyiimcnEGhRMcZKwxPHfAMcTCBEbhqoBdXHAyNSvVZwagTeImVWrcCpncCQGuWxiGCPZErUvjrqIzQYSMAUnhCvNRoCdFOrLNoWtLVTHadALvCOISzdfKNfmXQbMvuMfDfKDgNrQKZpxdjNZOdbxFuaGEpCeQslgaosqzUHJxEQftRLaWzuuRoTAdfeXjbGjCOpLRnlLhVTNPnPhjDyWegbkvOzOFDYMYMhUndmlIzoCLOdMRBZoRxzVTUAIdXZigoLlmGUjLSoHSVdfEMdTXEUmiOITNsxVnXUWmNPfitzxAjBkuVMnluoOnUdqswyuCZozXoxAfRcWVMmblfcPPHfTLEkHXQnWyMQydLGhtsSgdCFiRSmvTJfkpLvLBWIfwBjQTKxBiMlRTgNabJdxWIEFLVCdlqtSWUrmbASdXnXHBqtEbcUTgwvTHXdHRJyZzknQEBPxrYmwAXEgrsrUCqHyioVOYJuxpaNVeajeukkYAwEZsPzYcQPpWXvnNPHivSHSSYVjlUndxAFpCxLoOtryvLvGniqvPzLBXAPWQgSccXINwfTiVFglMUtPRWqfjorMQYyIUUJzrLLfxaTwfRcqdKDIfXZHCWJgYeRopRQtjGJjsTRrKamAgGMZKKOpxyKUsnZVvhhNRAGaGwxZoiykvMaQjElxwgueWmTSJmoezRUegUBzElOdZNcdasjzGoTXYzgVtVMRtVvswhfeFVUjPCcgeJXWyylbVzGigCHrNqOEdELTdiuZpaGGjYPCeekznQSmdknmrzFvbPLIrbFcCVlUgCVpLOpcWdZjZamKFKrLXTkqjizSnaqFuxMcLXPTbKNnWwkKBVlyqPfhvEHgXQehpOwriiwxGKvBFmmdOJNfMcCNWTAlOtLcMfKXkgikyHqiouJoAIXeFImwmKCTabkRCVtAFdlwIQfDueyDobfjokxBkIiBCviViLaWTFXHluvTMGqejeVkBAVmITjpvRgrCdSflpXRFWGaJlGMSPAOUvmdubXyweoVmdnUOiMxgEvNKCalLwPPmNnMfOvtZOaPsdjfZecsDiHKXCyJCAGyklpOWfTvsrDSbSGgWdNFsTrzQYkMOuDNTrgXFKJBloEClUJQgRqWgUeTmkogUwcAhDhGGCBSWxtXmLjmJFjtKURtTCxNOoEbYYuvKpwXSNUKvCzOXJomxxcltzWbUDymejntiPbtwJkjjLYQfgYrGYFUCtaiClkbYEhoNSPsMxLlMZcMJQvOgkEZoyBDJIuhafgcEIapXAQVgSbiJvUDHTwppEkmWWFeuCaqWFRhlCfTLpXVjnKFcTEXgkpZxQxobkpdWoaFOZtbyGDVFAjxmQohapTLsnlKjIgZrFsBgMqBnbaHelrDeWuEwqvkvYzbPgqvoWyKZeGlJRLyhbETrzTEWbTgjbrUtbKnDgEaQeuTLzZsaMCMMvjwbpDKoSgPLVUKpzaQgjdKuiipcvbOibcxRAAaNQScbbyqnxrTcRnHJgmrYICLhdBXvXeGbfAEXOaABYdxFqtKpXVMQpHXLtxCVMlxDJPUlJNOGvzFMyIRBFiEeSIejdBlyPArQERlKuEhYUGJirKvQefZLqUQXskRnbzUrwPLzstPxISsjLuFzsmfxziVesrSkEDNjepgVPUbHLGwtKIsyyjVQHxPHjdWdWQMaQwtZIBkChEAetDyBJeTtgzYHUURveRLLScKUhSJMoAXtrYgkdXGISnnAHvQtezKRKwaMmHajgEJZoWznEiZLZSsGLDGhxnEjpubPPxNLjCkbfYdGXUpXiTfaTaSDFnsHKWNzMqgxBBOshEWBowWCFkDCWvkWoTKMnEgjNopURJjwafPQoLNGBMAuCItMGZBoqiEUjeiosNsmYqJtGvpFgXWcCCKdRRvDihdYcTQheshcTUuSsvQWmwtaokIjaLbPmgBexZQFRIKAqvwbuXUNkbyMyseXBnZHfhUsFGSkRqYZVKTalohbMXsghRUDuysSMwFmPmMWFxCpISMWxIFEQSWtqqkumZGoANSOasHgJBEKwLJBxEnhhbwqqUcrqynAATewLteSGXPCwYfVQgGXtTpIbwSYrxBQGdxJMzfqRYDPKFPNyrqefGfSzBgzRDvLHSyXTRTXFOIqiyBpFexQDXBePJNDPpBicIRTBBtLquAlxYUWpuDbvmJSOjpnEGIWxgcbFdzzSKwnauiAxOvjjWULAdOMBtgOTcIayliaGytvVbZvVmyBWAJyqYcTnHUXyInpLaeIJceCyyBfIMUXXDGrKJadafwwQkVSKlWKGPjPFZDcWNIhleRaIXHDiIImdQPftZvZtwYxYcuOCffEypBzRtscpuqMwxGZvycKtevNJPBduBXIUSUooGgYgRtGaZTyrCGbkjFGxbRMDQGzxiGZDjcHWfOrQkJJGuJTRIGiKOBYSRTiouiAZWvhAWiSDDwTicHgvehsUtDftgBIJUMxLNHlvxBoFPceuOwqRdiELVybAOaWlrcBjVkJcxYPJpgIJGngjyUvFdnDCDBqxqmRYlIhDkyqhGbWbZoAOXpmALQzEwaahgMSlsrOajPlGSIKFUsyRDjPQcOoqJtjvNPLiHJECIFuhiieZyMJcQTckUhscJMuVdEziMfEgOmrHvuvivgMBeRRpLgkwwopLkRQIWJRZbYOsxrotLbudGLwgkKWANWwIwJNQdCVoBSiPnxjeHknuhsXcxDccrSnByzvXBUOAetHRQYyvqGLxWbwXYdrBfSBcNOSJhGTNscIAXpCLoACaQgcBTXzGtCiDnGLaZCWxIfwKdyJwbkxdeUjzpQrLwasIKLSLFMErfKPxQyQfiRYhhuxScwVlqzgsMlZuyoaFCuhMjIVDOeBHdkZYudadMChXqyiKUmkAPRPWSgdmNagCsooVpScswCenpBoCCjqXpBbDEhhvUVTfSLhgtKhASwGouuQeDzyjoXuxELQAmkVnGAAJxMahkARslprzGtdbkPrcXyhWwhWrrXXPRfKmjjNEYgHtmwctNbqrCUaJppplPnJETEyDbrmleiKLkgLJMuBpRlWIfeOoQCbGNOVmlMtZgYCGmsLcTkBvHJGUzlgyUjyXoNopRHMJeaHIcjRuXiLjagnhHjxSlJtVmgGRnvktdojVhHxwZvjieJCppvkavHWPcnbZtiMnvygAkBjiGBNmlrAYuaHkjwCoIszHmGONXqaxwJZVqOgquGAkJEXUnLtCdyrQwDGGOuuUUHWpraStbFMSYGrOSNLxLeNlVeTJkksolsMhVeuQRLjUdAmKJlwecCiHTuspPtVxUVzzVDuvPvWNquPLIhVdpUQVuiIGiYcfUANgHnoWQMSoQOMHlqNIkvQbgoqhHzfvcLpIyoxHIaxdLrZJgXAijynLvXEIaAizXcUiTPlaBhdpjYZeoaCHcrYUznynHPJpoPpgEKxjaAZlgpxjsnhNsQSPjRXzgygsNDuWnjCqnPLJJGkibUXGsPgUxZAwhYBWCdsQPWvtbcvDQRdXMxBMdVRXLpHGufsTQPXOloFIZkfDljsUUUxCiNQoYfuLwDNUzcrjIOSrMoWVmmHNynFbukYXEFLIpBfedpFjGHfXqYVuZbUnUjDLsWYrEVCKmvqQVaatsRnUosnABsmXrfvVMVTXitiYWUKtcdnZpYuGPPqoQrpDFmVuxMTknZQwOjhwElrfYDFKtbGvVszNbtDNpbFHAKKUFHZVuXRaRYeKWucYqXLiwoNvNBYXnaQZBTVGWIDGTaWfBrMrVVkyaXjotYYSQxzajEoWWcoJxlBwSxGODjsUeomYxHpuEpDylwYjndIsrwyyfAGyMVSxPtgttvWTfbstfMfCYrlFismGkAZvqbSnisILDcSlugVwbBkwAXopthpjqFbToNDuMccnEdSRByociaMtlbAVesZqEaHGNFaDenFwGWiGAqTOCSnXnSzneVjmHVeNBGuoOmMgcbgJBCpQPYmbHdkJPQdBlAmLLsgueEfLNGnZJFqfzkONnDHxIuJDMbUNoVwSFBBJwrHijsTMSqNsFPdjAXraRKgEDqDHWGzqWzrWpLwaUpuiguxpaxhIkPdjLCqOMhrYrLjyoCsNawRNcHSXhjtKNgMhYohRFIYQJfspJOmybuPhuQjRwNQeESRWPgJKhzrNdzbQiQbNfSIAViBdewwSDRaTKvZpbtThjYASfTUCIIhZQtxEoTlJsvTZQwalTTBgqLpfsyitrvwmKCJoZWOnQSZTpDlXEsInyeNyTaZYpvZPDBygFDGEztjPzVZDHtRKoTgZELUgEwsMyzfOsQEZNnsCvKWxckBddrMwfWUbjjHTvQvParGEFmxCCkQLcoabKjyokUpJyQnmkNDbNrOJdpUanzuTbzRkpcoFjhKhjqWqzmnfOlTjVoDpWFpjOEYbLPioIwfqoEtPAazEhmYsNmSsfsTIwOzrtggXhDkjPokcDUcfOZjnqauuzJOnRaOJhvPqDmUhnfrbHEcdfcaOLxxQbDePIzwqHMonfDlDqDAhazrhGJtxVuPDPZVnhJHSGBpmVFvahyuyKrpqvsTNSQxEbmssKJbYQkbXwsnAqZjSYPqDcrfORmttBvwUBPYIxLlmzeoMaelsCbImrasxwfFfFZdHeUdIRZKjMnNeneArMvLngyGjmcaowYiCctrIqUjAWwLaPFtBJGhHEhbVqJNIdKAGMPOltZIKEEBQTQhfvdiAHJeZMifwPMxTEHJqkgmHMmYPYqCarDoZerLtHgyWwJjeIlSYlISWvPrSciUXvxKSqWLKTRcWUURClgXyqQXWQvOWXTLUrziKQRjxTpnwRNQaYMIMMUXcTZrEGGhFXmmaaHZZmQIeQGBHoRjgAAZajnziDKkxziRrTuAsAEObpbwYDUcuILWFEuMsBcPwwMNdCeFNSDjbGvDYUOuPpLemtqLOlvxLPFnMYnCtssijrLQdoWsuereycVPkjVbtavKEAnlcJVzHruIoeWBcuydLeYyDLYeyYMOUtroZiGJRHRnLiSBLuGUNlzZLnhiWTdNGrlAVPoLoYsmTTLlpKdLqwnSxMIDXBHAxYeMrpyoNjvjlyPflmlOsLWtrmShLYMSRjhXkxrgwGaIXBuCWRxCgeuWyuIUSQqPwKMhHSBdFsYZKOsqZXXAVxXXJKFCniGXeQzNBbkEkcqowQgqhTuiPEyUFjarTkkFHDOuhLHUzZfxLwHIooIGkNPAXexdNwIuqSoSBhDeQLkPLiRuQMubHSqIgunJsBWHLBFsUoTNjZWQDDxEtAQNDYAdeiGpjEBVGIDGLvdMiECXnuielRZauFRBSmnpoGJhHCdavVKiYEOWLLAVcUzocBdkPaPCuvhWXUQSuAsgIBQAoROBzlGtaMIHsHoWxPqBvFCosnqLmfGeZazRxTiHWdwXAthYuAIdPSgbpuIVvROExXuhhvCcCmnxfGaqiJNNvzHbEWUlpgLyJHlRBFgPPJCaIAFkAlyqdwBfgdYRcoQGXZLvlsmMDxekdcmQIqBQVRGvHtYUzthgAtyrZvigUMkaDPIGSIFjzCkKJhEONIkRxkoPXAGmwBmHVpvPdwRaDGmTverKrwSsVLvfIjGMubztrSpnGdlFRbxgmhNeOjcMPFoApwePlgRabyllXdlTerRBKdbvYgqNDYYNchlwdWwyLlvQBOVIHfJlFVtmkDvinYkkeRJkscztzEKQsFOSmPnVgSNqSqndAVQJnnlqhJLbtxPZbxfYRRaCyWMCKfORKWGnjClFixcIQspwUWtrlJSiCZvKzdaIQturxnBGdLIREHDldUCdNdxnsHrClqLATvPhoZRtixXiQYejsarnKOoYIifvLeGISmmeQNCMAkqLxRQrnEkmgFLCNCjWCtrDMEIfczvJgtlGWDsTbSEUKvWEIhOhMszkXUCcVhACkLKQJqSxkujXpTshKYRmuadwaBQSvkIPFRPtDaSYvgJXxmsHFngRdxiQFgCugHlKOWXpJeTkDWuZhzFKedytKzEuUQDiJmwkYUvDYZpTWshnJdBlZmnoTKgcwFrasjBpQyPTAKPDBFPfLzCepkPTHTQAqVMMFXUunEgOjOyrcsbIZzPEREiymQYmBjiDtYCjAJVIQgHlhvYvLFXRjJwejJegVjoycbVqEvxKEdkLrFsoMxWeKBcHeMLcIvtZXXTJOXhpzaiMBTjBHVsOgNWzbRfAbAiNeEBpWnysbeNbuRpTRCAYWKcqcnzXWkRWvlVtHjwSObEWanCJSLrwZoBpNiTSTYntvJJZNCNspCFDqQnAMMqpvPQWtbpsaMwzECdxXcKbbeQkskLALCZrzCNfdYOxEayHHkRNF"
// // let matches = /[a-z]{4}[A-Z]{4}/.exec(text)
// // console.log(JSON.stringify(matches))

// let https = require('https')

// function next(code) {
//     var options = {
//         host: `challenge.hiringsolved.com`,
//         path: `/breadcrumbs/${code}`
//     }

//     https.get(options, function (res) {
//         var data = '';
//         res.on('data', function (chunk) {
//             data += chunk;
//         })
//         res.on('end', function () {
//             let nextCode = data.split(' ').pop()
//             console.log('----------------------')
//             console.log(data)
//             // console.log('nextCode: ' + nextCode)
//             if (nextCode != '12345') {
//                 next(nextCode)
//             }
//         })
//     }).on('error', function (e) {
//         console.log("Got error: " + e.message);
//     })
// }

// // next(62605)
// next(53781)

// // https://challenge.hiringsolved.com/monster