/*
This file was generated from ion source. Do not edit.
*/
import * as Location from '../Location';
import * as Null from './Null';
import * as Map from './Map';
import * as String from './String';
import * as Declaration from '../Declaration';
import * as Type from '../Type';
import * as Call from '../Call';
import * as Property from '../Property';
import * as _Array from './Array';
import * as Identifier from '../Identifier';
import * as RestElement from '../RestElement';
import * as Pattern from '../Pattern';
import * as Reference from '../Reference';
import * as Expression from '../Expression';
import * as Literal from '../Literal';
import * as Variable from '../Variable';
import * as ImportDeclaration from '../ImportDeclaration';
import * as Boolean from './Boolean';
import * as Number from './Number';
import * as PatternProperty from '../PatternProperty';
import * as Declarator from '../Declarator';
import * as Integer from './Integer';
import * as Class from './Class';
export type Location_Location_or_ion_Null_Null = Location.Location | Null.Null;
export type ___TemplateReference___ = Map.Map<String.String, Declaration.Declaration>;
export type Type_Type_or_ion_Null_Null = Type.Type | Null.Null;
export type Call_Call_or_Property_Property = Call.Call | Property.Property;
export type ion_types____TemplateReference____or_ion_Null_Null = _Array.Array<Call.Call | Property.Property> | Null.Null;
export type Identifier_Identifier_or_ion_Null_Null = Identifier.Identifier | Null.Null;
export type RestElement_RestElement_or_ion_Null_Null = RestElement.RestElement | Null.Null;
export type Pattern_Pattern_or_ion_types_RestElement_RestElement_or_ion_Null_Null = Pattern.Pattern | (RestElement.RestElement | Null.Null);
export type Pattern_Pattern_or_Reference_Reference = Pattern.Pattern | Reference.Reference;
export type Expression_Expression_or_ion_Null_Null = Expression.Expression | Null.Null;
export type Identifier_Identifier_or_Expression_Expression = Identifier.Identifier | Expression.Expression;
export type Pattern_Pattern_or_ion_types_Identifier_Identifier_or_Expression_Expression = Pattern.Pattern | (Identifier.Identifier | Expression.Expression);
export type Declaration_Declaration_or_ion_Null_Null = Declaration.Declaration | Null.Null;
export type Literal_Literal_or_ion_Null_Null = Literal.Literal | Null.Null;
export type Variable_Variable_or_ion_Null_Null = Variable.Variable | Null.Null;
export type ImportDeclaration_Specifier_or_ImportDeclaration_ImportDeclaration = ImportDeclaration.Specifier | ImportDeclaration.ImportDeclaration;
export type Literal_Literal_or_Identifier_Identifier = Literal.Literal | Identifier.Identifier;
export type ion_String_String_or_ion_Null_Null = String.String | Null.Null;
export type ion_Boolean_Boolean_or_ion_Null_Null = Boolean.Boolean | Null.Null;
export type ion_Number_Number_or_ion_types_ion_Boolean_Boolean_or_ion_Null_Null = Number.Number | (Boolean.Boolean | Null.Null);
export type ion_String_String_or_ion_types_ion_Number_Number_or_ion_types_ion_Boolean_Boolean_or_ion_Null_Null = String.String | (Number.Number | (Boolean.Boolean | Null.Null));
export type ion_Number_Number_or_ion_Null_Null = Number.Number | Null.Null;
export type PatternProperty_PatternProperty_or_RestElement_RestElement = PatternProperty.PatternProperty | RestElement.RestElement;
export type Property_Property_or_Type_Type = Property.Property | Type.Type;
export type Expression_Expression_or_Identifier_Identifier = Expression.Expression | Identifier.Identifier;
export type Pattern_Pattern_or_Expression_Expression = Pattern.Pattern | Expression.Expression;
export type Identifier_Identifier_or_Declarator_Declarator = Identifier.Identifier | Declarator.Declarator;
export type Expression_Expression_or_ion_types_Identifier_Identifier_or_Declarator_Declarator = Expression.Expression | (Identifier.Identifier | Declarator.Declarator);
export type Expression_Expression_or_ion_types_Identifier_Identifier_or_ion_Null_Null = Expression.Expression | (Identifier.Identifier | Null.Null);
export type ion_Integer_Integer___gte_0_ = Integer.Integer;
export type func__class__ion_Class_Class_instance__UNDEFINED__returns_ion_Boolean_Boolean = undefined;
export type func___returns_ion_String_String = undefined;
export type func_value__UNDEFINED__returns_ion_Boolean_Boolean = undefined;
export type ion_String_String___length_lte_this_length_ = String.String;
export type func___returns_ion_types_ion_String_String___length_lte_this_length_ = undefined;
export type func_pattern__ion_String_String__returns_ion_Boolean_Boolean = undefined;