// Generated by CoffeeScript 1.6.3
(function() {
  var AddStatement, Context, Expression, Operation, Statement, ion, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Operation = require('./Operation');

  Expression = require('./Expression');

  Statement = require('./Statement');

  Context = require('./Context');

  ion = require('../');

  module.exports = AddStatement = (function(_super) {
    __extends(AddStatement, _super);

    function AddStatement() {
      _ref = AddStatement.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AddStatement.prototype.activate = function() {
      var _this = this;
      AddStatement.__super__.activate.call(this);
      if (this.expression == null) {
        this.expression = Operation.createRuntime(this.context, this.args[0]);
      }
      return this.expression.watch(this.watcher != null ? this.watcher : this.watcher = function(value) {
        _this.value = value;
        return _this._update();
      });
    };

    AddStatement.prototype._addedValue = void 0;

    AddStatement.prototype._update = function() {
      if (this.value !== void 0) {
        return this._add();
      } else {
        return this._remove();
      }
    };

    AddStatement.prototype._add = function() {
      if (this._addedValue === void 0) {
        ion.add(this.context["this"], this.value);
        return this._addedValue = this.value;
      }
    };

    AddStatement.prototype._remove = function() {
      if (this._addedValue !== void 0) {
        ion.remove(this.context["this"], this._addedValue);
        return this._addedValue = void 0;
      }
    };

    AddStatement.prototype.deactivate = function() {
      AddStatement.__super__.deactivate.call(this);
      return this.expression.unwatch(this.watcher);
    };

    return AddStatement;

  })(Statement);

  module.exports.test = function() {
    var context, object, s;
    object = [false];
    context = new Context(object);
    s = Operation.createRuntime(context, {
      op: "block",
      args: [
        {
          op: 'add',
          args: [1]
        }, {
          op: 'if',
          args: [
            {
              op: 'member',
              args: [
                {
                  op: 'ancestor',
                  args: [0]
                }, 0
              ]
            }, {
              op: 'add',
              args: [2]
            }
          ]
        }, {
          op: 'add',
          args: [3]
        }, {
          op: 'add',
          args: [4]
        }
      ]
    });
    s.activate();
    console.log(JSON.stringify(object));
    Object.observe(object, function(changes) {
      return console.log(JSON.stringify(object));
    });
    object[0] = true;
    return "AddStatement";
  };

}).call(this);
