// Generated by CoffeeScript 1.6.3
(function() {
  var Construct,
    __hasProp = {}.hasOwnProperty;

  require('sugar');

  module.exports = Construct = (function() {
    function Construct(properties) {
      Object.merge(this, properties);
    }

    Construct.prototype.toJSON = function() {
      var json, key, value;
      json = {
        "$": this.constructor.name
      };
      for (key in this) {
        if (!__hasProp.call(this, key)) continue;
        value = this[key];
        json[key] = value;
      }
      return json;
    };

    Construct.prototype.dispose = function() {};

    return Construct;

  })();

}).call(this);
