// Generated by CoffeeScript 1.6.3
(function() {
  var Context, ion;

  ion = require('../');

  module.exports = Context = (function() {
    function Context(input, output, parent, additions) {
      var _ref;
      if (input == null) {
        input = global;
      }
      this.variables = {};
      this.input = input;
      this.output = output != null ? output : input;
      this.parent = parent;
      this.additions = (_ref = additions != null ? additions : parent != null ? parent.additions : void 0) != null ? _ref : [ion.count(this.output)];
    }

    Context.prototype.getInsertionIndex = function(addIndex) {
      var count, i, insertionIndex, _i;
      insertionIndex = 0;
      for (i = _i = 0; 0 <= addIndex ? _i <= addIndex : _i >= addIndex; i = 0 <= addIndex ? ++_i : --_i) {
        count = this.additions[i];
        if (count != null) {
          insertionIndex += count;
        }
      }
      return insertionIndex;
    };

    Context.prototype.setAdditionCount = function(addIndex, count) {
      return this.additions[addIndex] = count;
    };

    Context.prototype.input = null;

    Context.prototype.output = null;

    Context.prototype.parent = null;

    Context.prototype.variables = null;

    Context.prototype.additions = null;

    return Context;

  })();

}).call(this);
