// Generated by CoffeeScript 1.6.3
(function() {
  var Context;

  module.exports = Context = (function() {
    function Context(input, output, parent, additions) {
      this.variables = {};
      this.input = input;
      this.output = output != null ? output : input;
      this.parent = parent;
      this.additions = additions != null ? additions : parent != null ? parent.additions : void 0;
    }

    Context.prototype.input = null;

    Context.prototype.output = null;

    Context.prototype.parent = null;

    Context.prototype.variables = null;

    Context.prototype.additions = null;

    return Context;

  })();

}).call(this);
