// Generated by CoffeeScript 1.6.3
(function() {
  var Context;

  module.exports = Context = (function() {
    function Context(_this, parent) {
      this["this"] = _this;
      this.parent = parent;
      this.variables = {};
    }

    Context.prototype.parent = null;

    Context.prototype.variables = null;

    return Context;

  })();

}).call(this);
