// Generated by CoffeeScript 1.6.3
(function() {
  var DynamicExpression, Expression, ExpressionList, Operation, OperationExpression,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Operation = require('../Operation');

  Expression = require('./Expression');

  DynamicExpression = require('./DynamicExpression');

  ExpressionList = require('./ExpressionList');

  module.exports = OperationExpression = (function(_super) {
    __extends(OperationExpression, _super);

    function OperationExpression(properties) {
      OperationExpression.__super__.constructor.call(this, properties);
      this.expressionList = new ExpressionList(this.context, this.args);
    }

    OperationExpression.prototype.activate = function() {
      var _this = this;
      OperationExpression.__super__.activate.call(this);
      return this.expressionList.watch(this.watcher != null ? this.watcher : this.watcher = function(value) {
        _this.argumentValues = value;
        return _this.evaluate();
      });
    };

    OperationExpression.prototype.deactivate = function() {
      OperationExpression.__super__.deactivate.call(this);
      return this.expressionList.unwatch(this.watcher);
    };

    OperationExpression.prototype.evaluate = function() {
      var value;
      value = this.operation.evaluate.apply(this.operation, this.argumentValues);
      return this.setValue(value);
    };

    return OperationExpression;

  })(DynamicExpression);

  module.exports.test = function() {
    var e, op, result, watcher;
    op = Operation.getOperation("+");
    e = new OperationExpression({
      operation: op,
      args: [1, 2]
    });
    result = void 0;
    watcher = function(value) {
      return result = value;
    };
    e.watch(watcher);
    if (result !== 3) {
      throw "result != 3";
    }
  };

}).call(this);
