/*
This file was generated from ion source. Do not edit.
*/
import * as Location from '../Location';
import * as Null from './Null';
import * as Map from './Map';
import * as String from './String';
import * as Declaration from '../Declaration';
import * as Reference from '../Reference';
import * as TypeDefinition from '../TypeDefinition';
import * as TypeExpression from '../TypeExpression';
import * as Expression from '../Expression';
import * as Id from '../Id';
import * as IfStatement from '../IfStatement';
import * as BlockStatement from '../BlockStatement';
import * as _Array from './Array';
import * as ImportStep from '../ImportStep';
import * as Boolean from './Boolean';
import * as Number from './Number';
import * as _Object from './Object';
import * as Integer from './Integer';
import * as Class from './Class';
export type Location_Location_or_ion_Null_Null = Location.Location | Null.Null;
export type ___TemplateReference___ = Map.Map<String.String, Declaration.Declaration>;
export type Reference_Reference_or_ion_Null_Null = Reference.Reference | Null.Null;
export type TypeDefinition_TypeDefinition_or_ion_types_Reference_Reference_or_ion_Null_Null = TypeDefinition.TypeDefinition | (Reference.Reference | Null.Null);
export type TypeExpression_TypeExpression_or_ion_Null_Null = TypeExpression.TypeExpression | Null.Null;
export type Expression_Expression_or_ion_Null_Null = Expression.Expression | Null.Null;
export type Id_Id_or_ion_Null_Null = Id.Id | Null.Null;
export type IfStatement_IfStatement_or_ion_Null_Null = IfStatement.IfStatement | Null.Null;
export type BlockStatement_BlockStatement_or_ion_types_IfStatement_IfStatement_or_ion_Null_Null = BlockStatement.BlockStatement | (IfStatement.IfStatement | Null.Null);
export type ion_types____TemplateReference____or_ion_Boolean_Boolean = _Array.Array<ImportStep.ImportStep> | Boolean.Boolean;
export type Expression_Expression_or_Id_Id = Expression.Expression | Id.Id;
export type ion_Boolean_Boolean_or_ion_Null_Null = Boolean.Boolean | Null.Null;
export type ion_Number_Number_or_ion_types_ion_Boolean_Boolean_or_ion_Null_Null = Number.Number | (Boolean.Boolean | Null.Null);
export type ion_String_String_or_ion_types_ion_Number_Number_or_ion_types_ion_Boolean_Boolean_or_ion_Null_Null = String.String | (Number.Number | (Boolean.Boolean | Null.Null));
export type Id_Id_or_Expression_Expression = Id.Id | Expression.Expression;
export type ion_Object_Object_or_ion_String_String = _Object.Object | String.String;
export type Id_Id_or_ion_types_Expression_Expression_or_ion_Null_Null = Id.Id | (Expression.Expression | Null.Null);
export type TypeDefinition_TypeDefinition_or_Reference_Reference = TypeDefinition.TypeDefinition | Reference.Reference;
export type ion_Integer_Integer___gte_0_ = Integer.Integer;
export type func__class__ion_Class_Class_instance__UNDEFINED__returns_ion_Boolean_Boolean = undefined;
export type func___returns_ion_String_String = undefined;
export type func_value__UNDEFINED__returns_ion_Boolean_Boolean = undefined;
export type ion_String_String___length_lte_this_length_ = String.String;
export type func___returns_ion_types_ion_String_String___length_lte_this_length_ = undefined;
export type func_pattern__ion_String_String__returns_ion_Boolean_Boolean = undefined;