// Generated by CoffeeScript 1.6.3
(function() {
  var Template, parse, parser, preprocessor, template;

  require('sugar');

  Template = require('./Template');

  preprocessor = require('./preprocessor');

  parser = require('./parser');

  parse = function(input) {
    var ast, lineMapping, preprocessed;
    lineMapping = [];
    preprocessed = preprocessor.preprocess(input, lineMapping);
    ast = parser.parse(preprocessed);
    return ast;
  };

  template = function(input, name) {
    return new Template(parse(input), name);
  };

  exports._parse = parse;

  exports.template = template;

}).call(this);
