export const Id = "Id"
export const IdReference = "IdReference"
export const IdDeclaration = "IdDeclaration"
export const VariableDeclaration = "VariableDeclaration"
export const VariableDeclarator = "VariableDeclarator"